language: python
python:
  - "2.7"
env:
  - TOXENV=py26-1.4
  - TOXENV=py27-1.4
  - TOXENV=py26-1.5
  - TOXENV=py27-1.5
install:
  - pip install -q --use-mirrors tox==1.4.2
before_script:
  - psql -c 'create database django_timepiece;'
script:
  - tox
